### ISSUE TITLE
Attempt to read from field 'android.app.Application io.castle.android.Castle.application'

### ISSUE THREAD

**Issue by MuhammadUsman786786** [castle/castle-react-native#19]
i have installed the in my react native project, i am facing the issue. And there is not proper documentation available for the integration

**Error:**
App is crashing on launch, crash image is below

![WhatsApp Image 2021-03-26 at 9 28 22 PM](https://user-images.githubusercontent.com/29137881/112663727-f99e7d80-8e7a-11eb-9d86-083b2540bbe2.jpeg)

**package.json**
```
{
  "name": "mobile",
  "version": "0.1.13",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@castleio/react-native-castle": "^1.0.4",
    "@react-native-async-storage/async-storage": "^1.13.2",
    "@react-native-clipboard/clipboard": "^1.6.0",
    "@react-native-firebase/analytics": "^11.1.2",
    "@react-native-firebase/app": "^10.8.1",
    "@react-native-firebase/messaging": "^10.8.1",
    "@react-native-firebase/remote-config": "^11.1.2",
    "@sentry/react-native": "^2.3.0",
    "axios": "^0.21.1",
    "moment": "^2.29.1",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-check-box": "^2.1.7",
    "react-native-device-info": "^7.4.0",
    "react-native-dropdown-picker": "^4.0.2",
    "react-native-exit-app": "^1.1.0",
    "react-native-fast-image": "^8.3.4",
    "react-native-fs": "^2.16.6",
    "react-native-gesture-handler": "^1.9.0",
    "react-native-get-random-values": "^1.5.1",
    "react-native-keyboard-aware-scrollview": "^2.1.0",
    "react-native-navigation": "^7.5.0",
    "react-native-normalize": "^1.0.1",
    "react-native-reanimated": "^2.0.0-alpha.9.2",
    "react-native-simple-dialogs": "^1.4.0",
    "react-native-smart-tip": "^2.2.1",
    "react-native-snackbar": "^2.3.1",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^12.1.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-tab-view": "^2.15.2",
    "react-native-vector-icons": "^7.1.0",
    "react-redux": "^7.2.2",
    "redux": "^4.0.5",
    "redux-persist": "^6.0.0",
    "redux-persist-fs-storage": "^1.3.0",
    "redux-saga": "^1.1.3",
    "redux-saga-routines": "^3.2.3",
    "redux-thunk": "^2.3.0",
    "rn-fetch-blob": "^0.12.0",
    "socket.io-client": "^3.0.5",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.15.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "16.13.1",
    "reactotron-react-native": "^5.0.0",
    "reactotron-redux": "^3.1.3",
    "reactotron-redux-saga": "^4.2.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
**project code**
```

import {env} from '../../environment';
import Castle from '@castleio/react-native-castle';

export const getCastleInfo = async () => {
  try {
    await Castle.configureWithPublishableKey(env.CASTLE_PUBLISH_KEY);
    const clientIdHeaderName = await Castle.clientIdHeaderName();
    const clientId = await Castle.clientId();
    return {clientIdHeaderName, clientId};
  } catch (e) {
    return {};
  }
};

export const clearCastleSession = async () => {
  try {
    await Castle.reset();
  } catch (e) {}
};

export const setCastleIdentity = async ({userId}) => {
  try {
    await Castle.identify(userId, {});
  } catch (e) {}
};

export const setCastleScreen = async (routeEvent) => {
  try {
    const {componentName} = routeEvent || {};
    await Castle.screen(componentName);
  } catch (e) {}
};

```

**crash logs on android studio**
**check the 8th line in the below logs: you will find the actual issue**

  ```
 Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
2021-03-26 21:23:34.430 10331-10436/testapp.io E/ReactNativeJNI: logMarker RUN_JS_BUNDLE_END
2021-03-26 21:23:34.746 10331-10331/testapp.io E/unknown:ReactNative: ReactInstanceManager.attachRootViewToInstance()
2021-03-26 21:23:34.748 10331-10331/testapp.io E/unknown:ReactRootView: runApplication: call AppRegistry.runApplication
2021-03-26 21:23:34.801 10331-10331/testapp.io D/ViewRootImpl@7f5664e[MainActivity]: Relayout returned: old=(0,0,720,1520) new=(0,0,720,1520) req=(720,1520)0 dur=23 res=0x1 s={true 3752544256} ch=false
2021-03-26 21:23:35.018 10331-10436/testapp.io I/ReactNativeJS: Running "splash" with {"initialProps":{"componentId":"Component2"},"rootTag":11}
2021-03-26 21:23:35.083 10331-10438/testapp.io E/unknown:ReactNative: CatalystInstanceImpl caught native exception
    java.lang.NullPointerException: Attempt to read from field 'android.app.Application io.castle.android.Castle.application' on a null object reference
        at io.castle.android.Castle.createContext(Castle.java:448)
        at io.castle.android.api.model.Event.<init>(Event.java:41)
        at io.castle.android.api.model.ScreenEvent.<init>(ScreenEvent.java:21)
        at io.castle.android.Castle.screen(Castle.java:233)
        at com.reactnativecastle.CastleModule.screen(CastleModule.kt:101)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:237)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)
2021-03-26 21:23:35.085 10331-10438/testapp.io E/unknown:ReactNative: Exception in native call
    java.lang.NullPointerException: Attempt to read from field 'android.app.Application io.castle.android.Castle.application' on a null object reference
        at io.castle.android.Castle.createContext(Castle.java:448)
        at io.castle.android.api.model.Event.<init>(Event.java:41)
        at io.castle.android.api.model.ScreenEvent.<init>(ScreenEvent.java:21)
        at io.castle.android.Castle.screen(Castle.java:233)
        at com.reactnativecastle.CastleModule.screen(CastleModule.kt:101)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:237)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by marysieek** [comment]
Dear @MuhammadUsman786786  and @Massad, 

thank you for your bug report and for providing the stacktrace.

For future reference, our integration guide is available [here](https://docs.castle.io/mobile-fingerprinting/). 

The `configureWithPublishableKey` method was mistakenly unexposed in the Castle type. Because of that, it was not accessible even though our documentation mentioned its existence. I issued a PR with a bugfix.  I do apologize for any inconvenience this issue caused.

I managed to recreate the issue by calling the `setCastleScreen` method before the `getCastleInfo` call. After installing the app, please make sure that Castle is initialized with the proper publishable key before calling any other method.

I will release the new package version as soon as the mentioned PR gets approved.

**Comment by MuhammadUsman786786** [comment]
Thanks maria for the PR. I hope it will be merged soon

**Comment by MuhammadUsman786786** [comment]
@marysieek yeah this is working fine now
